const val RELEASE_USER = "hendraanggrian"
const val RELEASE_ARTIFACT = "dispatcher"
const val RELEASE_GROUP = "com.$RELEASE_USER.$RELEASE_ARTIFACT"
const val RELEASE_VERSION = "0.1"
const val RELEASE_DESC = "Direct Android activity and permission result"
const val RELEASE_WEBSITE = "https://github.com/$RELEASE_USER/$RELEASE_ARTIFACT"
